# Google App Engine configuration (alternative to Cloud Run)
runtime: python311

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  FLASK_DEBUG: 'False'

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

